# Generated by Django 2.2 on 2020-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_producer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
